### ISSUE TITLE
Ve výpisu Aktuální chybí kus programu [AF15]

### ISSUE THREAD

**Issue by Aurielle** [Condroidapp/android#59]
V programu pro Animefest 2015 chybí při scrollování část programu na sobotu mezi 08:00 a 13:30. Ve výpisu všech i přes filtry/hledání chybějící program najdu, takže ta data tam jsou… Aktualizaci jsem provedl taky.

Nejspíš je bug v mechanizmu, který načítá další program, protože sobota 08:00 je to poslední, co se zobrazí, pak aplikace načítá dál. Nepokoušel jsem se na telefonu posouvat datum, jestli se problém projevuje i když bych měl třeba sobotu ráno nebo pátek večer, ale bug je to pořád.

**Comment by janlanger** [comment]
Jj, je tam bug. Tak jak řikáš, když se donačítají další pořady tak je část vynechaná.
